apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: sentiment-prometheus   # UID fisso e leggibile
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false